export const CLEAR_SELECTED_CELLS = "CELLS/CLEAR_SELECTED_CELLS"
export const SELECT_COL = "CELLS/SELECT_COL"
export const UNSELECT_COLS = "CELLS/UNSELECT_COLS"
export const ADD_SELECTED_CELLS = "CELLS/ADD_SELECTED_CELLS"

export const SET_CELLS = "ITEMS/SET_CELLS"
export const CLEAR_SELECTED_ITEMS = "ITEMS/CLEAR_SELECTED_ITEMS"
export const SELECT_ALL_ITEMS = "ITEMS/SELECT_ALL_ITEMS"
export const UNSELECT_ALL_ITEMS = "ITEMS/UNSELECT_ALL_ITEMS"
