export const CLEAR_SELECTED_CELLS = "CELLS/CLEAR_SELECTED_CELLS"
export const CLEAR_SELECTED_ITEMS = "ITEMS/CLEAR_SELECTED_ITEMS"
export const SELECT_COL = "CELLS/SELECT_COL"
export const UNSELECT_COLS = "CELLS/UNSELECT_COLS"
